//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Judging_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingJudge7
    {
        public string ContestantNo { get; set; }
        public Nullable<decimal> Personality { get; set; }
        public Nullable<decimal> Wit { get; set; }
    }
}
