//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Judging_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Top10Winners
    {
        public string ContestantNo { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> TotalScore1 { get; set; }
        public Nullable<decimal> TotalScore2 { get; set; }
        public Nullable<decimal> TotalScore3 { get; set; }
        public Nullable<decimal> TotalScore4 { get; set; }
        public Nullable<decimal> TotalScore5 { get; set; }
        public Nullable<decimal> TotalScore6 { get; set; }
        public Nullable<decimal> TotalScore7 { get; set; }
        public Nullable<decimal> FinalScore { get; set; }
    }
}
